In [3]:
import torch
import numpy as np
torch.__version__

'2.1.2'

In [8]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [49]:
my_tensor = torch.tensor([1, 2, 3, 4], 
                         dtype=torch.float32, 
                         device=device,
                         requires_grad=False)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([1., 2., 3., 4.])
torch.float32
cpu
torch.Size([4])
False


In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [11]:
scalar.shape

torch.Size([])

In [174]:
vector = torch.tensor([3, 4])
vector

tensor([3, 4])

In [133]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [178]:
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])
matrix, matrix.shape, matrix.shape[0], matrix.size(), matrix.size(0)

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]),
 3,
 torch.Size([3, 2]),
 3)

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([3, 2])

In [17]:
matrix[0][1]

tensor(2)

In [18]:
tensor = torch.tensor([
    [
      [1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [19]:
tensor.ndim

3

In [21]:
tensor.shape

torch.Size([2, 3, 3])

In [23]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
tensor[0].shape

torch.Size([3, 3])

In [27]:
torch.seed()

9142274306024453846

In [17]:
# Initilizes a 2 x 3 matrix with values from a uniform distribution in the interval 0 and 1
random_ten = torch.rand(2, 3)
random_ten

tensor([[0.0418, 0.9044, 0.3415],
        [0.4456, 0.5843, 0.8203]])

In [15]:
img_tensor = torch.rand(size=(224, 224, 3))
img_tensor

tensor([[[0.0861, 0.4304, 0.7414],
         [0.0043, 0.0617, 0.9759],
         [0.1169, 0.9636, 0.3015],
         ...,
         [0.8511, 0.4184, 0.1025],
         [0.2835, 0.4853, 0.8447],
         [0.4642, 0.4922, 0.6898]],

        [[0.7302, 0.7550, 0.0224],
         [0.8113, 0.0515, 0.4935],
         [0.0553, 0.0152, 0.8865],
         ...,
         [0.4499, 0.4243, 0.7271],
         [0.1171, 0.5352, 0.1077],
         [0.1378, 0.7569, 0.3838]],

        [[0.1410, 0.7535, 0.2243],
         [0.4570, 0.3784, 0.1504],
         [0.7367, 0.2403, 0.4862],
         ...,
         [0.9857, 0.6892, 0.9984],
         [0.0191, 0.3054, 0.2712],
         [0.8671, 0.3491, 0.8803]],

        ...,

        [[0.9041, 0.1340, 0.8501],
         [0.4060, 0.0228, 0.5797],
         [0.1723, 0.1655, 0.9708],
         ...,
         [0.2878, 0.5997, 0.1605],
         [0.7654, 0.7536, 0.8896],
         [0.9905, 0.2637, 0.3123]],

        [[0.8565, 0.2161, 0.8834],
         [0.9009, 0.7175, 0.7054],
         [0.

In [16]:
empty = torch.empty(size=(3, 3))
empty

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [47]:
zeroes = torch.zeros(2, 4)
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [49]:
ones = torch.ones(2, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [50]:
zeroes * ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [51]:
ones.dtype

torch.float32

In [19]:
# Identity matrix (I)
identity = torch.eye(3, 3)
identity

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [28]:
diagonal = torch.diag(torch.ones(3))
diagonal

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [62]:
torch.arange(start=2, end=21, step=2)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
torch.linspace(start=0.1, end=1, steps=10) # 10 values between 0.1 and 1

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [63]:
torch.zeros_like(identity)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
# Creates a 1 x 5 tensor with normally distributed values with a mean of 0 and standard deviation of 1
normal = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
normal

tensor([[ 1.9598, -2.1323, -0.2340, -1.7366,  1.1864]])

In [39]:
# Creates a 1 x 5 tensor with uniformly distributed values 
# with a lower value of 0 and upper value of 1 for the uniform distribution
uniform = torch.empty(size=(1, 5)).uniform_(0, 1) # lower of 0 and upper value of 1 for the uniform distribution
uniform, uniform.dtype

(tensor([[0.2234, 0.8457, 0.4750, 0.9848, 0.4335]]), torch.float32)

In [42]:
tensor = torch.arange(6)
print(tensor, tensor.dtype)

print(tensor.bool())  # converts tensor to boolean values
print(tensor.short()) # converts to int16
print(tensor.long())  # converts to int64
print(tensor.half())  # converts to float16
print(tensor.float()) # converts to float32
print(tensor.double()) # converts to float64

tensor([0, 1, 2, 3, 4, 5]) torch.int64
tensor([False,  True,  True,  True,  True,  True])
tensor([0, 1, 2, 3, 4, 5], dtype=torch.int16)
tensor([0, 1, 2, 3, 4, 5])
tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float16)
tensor([0., 1., 2., 3., 4., 5.])
tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [46]:
int32_tensor = torch.tensor([3, 4, 5, 6], dtype=torch.int32)
int32_tensor

tensor([3, 4, 5, 6], dtype=torch.int32)

In [47]:
# Convert int32 tensor to int64 tensor
int64_tensor = int32_tensor.type(torch.int64)
int64_tensor, int64_tensor.dtype

(tensor([3, 4, 5, 6]), torch.int64)

In [73]:
int64.reshape(-1, 1)

tensor([[3],
        [4],
        [5],
        [6]])

In [74]:
int64.device

device(type='cpu')

In [76]:
int64.size()

torch.Size([4])

In [77]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [78]:
ones + 2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [91]:
a = torch.tensor([[2, 4, 5, 6]])
print(a)
ones * a


tensor([[2, 4, 5, 6]])


tensor([[2., 4., 5., 6.],
        [2., 4., 5., 6.]])

In [98]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
a.reshape(-1, 1)

tensor([[1],
        [2],
        [3]])

In [100]:
%%time
torch.matmul(a.reshape(-1, 1), b.reshape(1, 3))

CPU times: user 800 µs, sys: 233 µs, total: 1.03 ms
Wall time: 836 µs


tensor([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]])

In [102]:
b @ a

tensor(32)

In [107]:
torch.mm(a.reshape(-1, 1).T, b.reshape(-1, 1))

tensor([[32]])

In [109]:
rand = torch.rand(3,2)
rand

tensor([[0.1570, 0.7430],
        [0.5915, 0.7914],
        [0.4836, 0.5175]])

In [110]:
rand.T

tensor([[0.1570, 0.5915, 0.4836],
        [0.7430, 0.7914, 0.5175]])

In [112]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [126]:
torch.max(ones, axis=1, keepdims=True)

tensor([[0],
        [0],
        [0]])

In [144]:
a = torch.tensor([
        [1., 2., 1., 1.],
        [1., 1., 1., 8.],
        [9., 1., 1., 2.]])
a

tensor([[1., 2., 1., 1.],
        [1., 1., 1., 8.],
        [9., 1., 1., 2.]])

In [130]:
a.argmax(axis=0)

tensor([2, 0, 0, 1])

In [131]:
a.argmax(axis=1)

tensor([1, 3, 0])

In [132]:
a.mean()

tensor(2.4167)

In [133]:
a

tensor([[1., 2., 1., 1.],
        [1., 1., 1., 8.],
        [9., 1., 1., 2.]])

In [134]:
a.reshape(4, 3)

tensor([[1., 2., 1.],
        [1., 1., 1.],
        [1., 8., 9.],
        [1., 1., 2.]])

In [145]:
# View is jsut a view into the origional tesnor, so modifying view
# will change the underlying or original tensor. While reshape creates 
# a brand new tensor of the specified shape
view = a.view(4, 3)
view

tensor([[1., 2., 1.],
        [1., 1., 1.],
        [1., 8., 9.],
        [1., 1., 2.]])

In [146]:
# Modifying view will modify the undelying or original tensor.
view[0][0] = -9999

In [147]:
view

tensor([[-9.9990e+03,  2.1120e+03,  1.0000e+00],
        [ 2.1110e+03,  2.1110e+03,  1.0000e+00],
        [ 2.1110e+03,  2.1180e+03,  9.0000e+00],
        [ 2.1110e+03,  2.1110e+03,  2.0000e+00]])

In [148]:
# Modifying view above modifies the underlying tensor.
a

tensor([[-9.9990e+03,  2.1120e+03,  1.0000e+00,  2.1110e+03],
        [ 2.1110e+03,  1.0000e+00,  2.1110e+03,  2.1180e+03],
        [ 9.0000e+00,  2.1110e+03,  2.1110e+03,  2.0000e+00]])

In [149]:
a = torch.tensor([
        [1., 2., 1., 1.],
        [1., 1., 1., 8.],
        [9., 1., 1., 2.]
])

In [169]:
b = torch.ones(2, 2)
b

tensor([[1., 1.],
        [1., 1.]])

In [174]:
c = torch.stack([b, b], dim=1)

In [175]:
c.shape

torch.Size([2, 2, 2])

In [146]:
# Moving on to another operation, let's say we want to add two tensors dimensions togethor
x1 = torch.rand(2, 5)
x2 = torch.rand(2, 5)
print(torch.cat((x1, x2), dim=0).shape)  # Shape: 4x5
print(torch.cat((x1, x2), dim=1).shape)  # Shape 2x10

torch.Size([4, 5])
torch.Size([2, 10])


In [149]:
x1 = torch.rand(2, 5)
# Let's say we want to unroll x1 into one long vector with 10 elements, we can do:
z = x1.view(-1)  # And -1 will unroll everything
z.shape, z

(torch.Size([10]),
 tensor([0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542, 0.3278,
         0.6532]))

In [150]:
# If we instead have an additional dimension and we wish to keep those as is we can do:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(
    batch, -1
)  # And z.shape would be 64x10, this is very useful stuff and is used all the time

z.shape

torch.Size([64, 10])

In [153]:
# Let's say we want to switch x axis so that instead of 64x2x5 we have 64x5x2
# I.e we want dimension 0 to stay, dimension 1 to become dimension 2, dimension 2 to become dimension 1
# Basically you tell permute where you want the new dimensions to be, torch.transpose is a special case
# of permute (why?)

x = torch.rand((64, 2, 5))

z = x.permute(0, 2, 1)
z.shape

torch.Size([64, 5, 2])

In [154]:
# Let's say we want to add an additional dimension
x = torch.arange(10)  # Shape is [10], 
# let's say we want to add an additional so we have 1x10
print(x.unsqueeze(0).shape)  # 1x10
print(x.unsqueeze(1).shape)  # 10x1

torch.Size([1, 10])
torch.Size([10, 1])


In [158]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
x.shape

torch.Size([1, 1, 10])

In [161]:
# Let's say we have x which is 1x1x10 and we want to remove a dim so we have 1x10
x = torch.arange(10).unsqueeze(0).unsqueeze(1) # 1x1x10

# Perhaps unsurprisingly
z = x.squeeze(1)  # can also do .squeeze(0) both returns 1x10
z.shape

torch.Size([1, 10])

In [180]:
a = torch.tensor([[1, 2, 3]])
a.shape

torch.Size([1, 3])

In [183]:
b = a.squeeze()
b

tensor([1, 2, 3])

In [187]:
b.unsqueeze(dim=1)

tensor([[1],
        [2],
        [3]])

In [171]:
x = torch.rand((64, 2, 5))

# Splits x last dimension into chunks of 2 (since 5 is not integer div by 2) the last dimension
# will be smaller, so it will split it into two tensors: 64x2x3 and 64x2x2
z = torch.chunk(x, chunks=2, dim=2)
print("Chunk for dim=2")
print(len(z))
print(z[0].shape)
print(z[1].shape)

z = torch.chunk(x, chunks=2, dim=0)
print("----"*10)
print("Chunk for dim=0")
print(len(z))
print(z[0].shape)
print(z[1].shape)

z = torch.chunk(x, chunks=2, dim=1)
print("----"*10)
print("Chunk for dim=1")
print(len(z))
print(z[0].shape)
print(z[1].shape)

Chunk for dim=2
2
torch.Size([64, 2, 3])
torch.Size([64, 2, 2])
----------------------------------------
Chunk for dim=0
2
torch.Size([32, 2, 5])
torch.Size([32, 2, 5])
----------------------------------------
Chunk for dim=1
2
torch.Size([64, 1, 5])
torch.Size([64, 1, 5])


In [43]:
array = np.arange(1, 10, 2)
array

array([1, 3, 5, 7, 9])

In [44]:
torch_arr = torch.from_numpy(array)
torch_arr

tensor([1, 3, 5, 7, 9])

In [45]:
numpy_arr = torch_arr.numpy()
numpy_arr

array([1, 3, 5, 7, 9])

In [210]:
torch.manual_seed(42)
print(torch.rand(2, 1))
print(torch.rand(1, 2))

tensor([[0.8823],
        [0.9150]])
tensor([[0.3829, 0.9593]])


In [212]:
torch.seed()

256341790350952121

In [213]:
torch.cuda.is_available()

False

In [214]:
torch.cuda.device_count()

0

In [215]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [218]:
torch.randn(1)

tensor([1.4553])

In [82]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([5, 2, 7])

In [83]:
torch.eq(x, y) # Element wise comparison

tensor([False,  True, False])

In [54]:
# Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)

# or 
z2 = torch.add(x, y)

# or 
z3 = x + y

# Subtraction
z = x - y

In [56]:
# Division
torch.true_divide(x, y) # element wise division of similar shape tensors

tensor([0.2000, 0.3333, 0.4286])

In [60]:
# Inplace operation. Mutates the tensor inplace rather than creating a copy

t = torch.tensor([1, 2, 3])
t.add_(x)
print(t)

t += x # Inplace addition
print(t)
t = t +x # Not an inplace addition will create a copy


tensor([2, 4, 6])
tensor([3, 6, 9])


In [61]:
# Exponentiation
z = x.pow(2)
# or
z = x ** 2

In [62]:
# -- Matrix Multiplication --
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)  # Matrix multiplication of x1 and x2, out shape: 2x3
x3 = x1.mm(x2)  # Similar as line above

In [63]:
# -- Matrix Exponentiation --
matrix_exp = torch.rand(5, 5)
print(
    matrix_exp.matrix_power(3)
)  # is same as matrix_exp (mm) matrix_exp (mm) matrix_exp

tensor([[2.5273, 1.9222, 3.9768, 2.8776, 3.0812],
        [3.0035, 2.2241, 4.3978, 3.1160, 3.5718],
        [2.2797, 2.1039, 3.5684, 2.2179, 3.0192],
        [2.2168, 1.9030, 3.5177, 2.2935, 2.8891],
        [3.3500, 2.9312, 5.1180, 3.4360, 4.2310]])


In [66]:
# -- Element wise Multiplication --
z = x * y  # z = [9, 16, 21] = [1*9, 2*8, 3*7]
z

tensor([ 5, 12, 21])

In [67]:
# -- Dot product --
z = torch.dot(x, y)  # Dot product, in this case z = 1*9 + 2*8 + 3*7
z

tensor(38)

In [68]:
# -- Batch Matrix Multiplication --
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)  # Will be shape: (b x n x p)
out_bmm.shape

torch.Size([32, 10, 30])

In [85]:
# -- Example of broadcasting --

# Along the rows (axis=0) (axis 0 can be thought of as the vertical axis or Y axis).
# i.e doing the operation along the 0 or y axis
# Along the rows means that we are adding more rows to the tensor, adding rows while walking along the
# vertical or Y or 0 axis.

# Along the columns (axis=1) (axis 1 can be thought of as the horizontal axis or X axis).
# i.e doing the operation along the 1 or X axis
# Along the cols means that we are adding one or more cols together, adding cols while walking along the
# horizontal or X or 1 axis.



x1 = torch.rand((5, 5))
x2 = torch.ones((1, 5))
z = (
    x1 + x2
) 
# Shape of z is 5x5: How? The 1x5 vector (x2) is added to each row in 
# the 5x5 (x1) element wise. i.e x2 element wise add to each row of x2

print(x1)
print(z)

tensor([[0.5136, 0.6057, 0.4847, 0.6421, 0.7427],
        [0.5926, 0.0698, 0.1602, 0.4507, 0.8929],
        [0.5745, 0.7654, 0.8543, 0.7686, 0.5404],
        [0.8259, 0.2406, 0.2763, 0.6990, 0.9031],
        [0.3782, 0.6200, 0.1005, 0.7110, 0.1221]])
tensor([[1.5136, 1.6057, 1.4847, 1.6421, 1.7427],
        [1.5926, 1.0698, 1.1602, 1.4507, 1.8929],
        [1.5745, 1.7654, 1.8543, 1.7686, 1.5404],
        [1.8259, 1.2406, 1.2763, 1.6990, 1.9031],
        [1.3782, 1.6200, 1.1005, 1.7110, 1.1221]])


In [74]:
z = (
    x1**x2
)  # Shape of z is 5x5: How? Broadcasting! Element wise exponentiation for every row

z

tensor([[0.4324, 0.1782, 0.5311, 0.0352, 0.9085],
        [0.9180, 0.1166, 0.6966, 0.7871, 0.0706],
        [0.7150, 0.5632, 0.9611, 0.5270, 0.4856],
        [0.5289, 0.6852, 0.1430, 0.8764, 0.8636],
        [0.8717, 0.1869, 0.9536, 0.3235, 0.0133]])

In [88]:
# Other useful tensor operations
sum_x = torch.sum(
    x, dim=0
)  # Sum of x across dim=0 (which is the only dim in our case), sum_x = 6

sum_x1 = torch.sum(
    x1, dim=0, keepdims=True
)
sum_x1.shape

torch.Size([1, 5])

In [91]:
# Other useful tensor operations

values, indices = torch.max(x, dim=0)  # Can also do x.max(dim=0)
values, indices = torch.min(x, dim=0)  # Can also do x.min(dim=0)
abs_x = torch.abs(x)  # Returns x where abs function has been applied to every element
z = torch.argmax(x, dim=0)  # Gets index of the maximum value. Similar to second returned value of max operation
z = torch.argmin(x, dim=0)  # Gets index of the minimum value
mean_x = torch.mean(x.float(), dim=0)  # mean requires x to be float
z = torch.eq(x, y)  # Element wise comparison, in this case z = [False, True, False]
sorted_y, indices = torch.sort(y, dim=0, descending=False) # sorted_y and indices that we need to swap so that it becomes sorted

z = torch.clamp(x, min=0)
print(z)
# All values < 0 set to 0 and values > 0 unchanged (this is exactly ReLU function)
# If you want to values over max_val to be clamped, do torch.clamp(x, min=min_val, max=max_val)

z = torch.clamp(x, max=2)
print(z)

tensor([1, 2, 3])
tensor([1, 2, 2])


In [93]:
x = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)  # True/False values
z = torch.any(x)  # will return True if atleast one vlaue in the tensor is True, can also do x.any() instead of torch.any(x)
print(z)
z = torch.all(
    x
)  # will return False (since not all are True), can also do x.all() instead of torch.all()
   # Returns True if all the values in the Tensor are true
print(z)

tensor(True)
tensor(False)


 ============================================================= 
                                   Tensor Indexing                        
 ============================================================= 

In [94]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

x.shape

torch.Size([10, 25])

In [98]:
# Get first examples features
# Get first row and all cols
x[0].shape  # shape [25], this is same as doing x[0,:]

torch.Size([25])

In [99]:
# Get the first feature for all examples
# Get all rows but first col of each row
x[:, 0].shape  # shape [10]

torch.Size([10])

In [100]:
# For example: Want to access third example in the batch and the first ten features
x[2, 0:10].shape  # shape: [10]

torch.Size([10])

In [101]:
# For example we can use this to, assign certain elements
x[0, 0] = 100

In [102]:
# Fancy Indexing
x = torch.arange(10)
print(x)
indices = [2, 5, 8]
print(x[indices])  # x[indices] = [2, 5, 8]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 5, 8])


In [118]:
torch.manual_seed(42)
x = torch.rand((3, 5))
print(x)

# In the first block, rows = torch.tensor([0, 1]) selects rows 0 and 1, 
# and cols = torch.tensor([4, 0]) selects columns 4 and 0. 
# So, x[rows, cols] accesses the elements at (0, 4) and (1, 0) 
# in the tensor x.
rows = torch.tensor([0, 1]) # Give me 0th row and 1st row 
cols = torch.tensor([4, 2]) # Give me 4th col and 0th col
print(x[rows, cols])  # Gets second row fifth column and first row first column


# In the second block, rows = torch.tensor([1, 0]) selects rows 1 and 0, 
# and cols = torch.tensor([4, 0]) still selects columns 4 and 0. 
# So, x[rows, cols] accesses the elements at (1, 4) and (0, 0) in the tensor x.
rows = torch.tensor([1, 0]) 
cols = torch.tensor([4, 2]) 
print(x[rows, cols])  # Gets second row fifth column and first row first column



tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])
tensor([0.3904, 0.7936])
tensor([0.1332, 0.3829])


In [122]:
# More advanced indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])  # will be [0, 1, 9]
print(x[(x > 2) & (x % 2 == 0)]) # [4, 6, 8
print(x[x.remainder(2) == 0])  # will be [0, 2, 4, 6, 8]

tensor([0, 1, 9])
tensor([4, 6, 8])
tensor([0, 2, 4, 6, 8])


In [127]:
# Useful operations for indexing
torch.where(x > 5, x, x * 2) 
# gives [0, 2, 4, 6, 8, 10, 6, 7, 8, 9], 
# all values x > 5 yield x, else x*2
# Means returns all the values in x and for each value return
# the same value as it is if x > 5 else returns x*2 in place
# of that element.



tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [136]:
x = torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique()  # x = [0, 1, 2, 3, 4]
x

tensor([0, 1, 2, 3, 4])

In [139]:
print(
    x.ndimension()
)  
# # The number of dimensions, in this case 1. if x.shape is 5x5x5 ndim would be 3



1


In [142]:
torch.manual_seed(42)
x = torch.rand((3, 5))

# The total number of elements in x
x.numel()

15